version: '3.5'

services:
  rundeck:
    #image: rundeck/rundeck:3.3.4
    hostname: rundeck
    links:
      - mysql
    env_file: .env
    build:
      context: .
    environment:
      #RUNDECK_DATABASE_DRIVER: com.mysql.jdbc.Driver
      RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
      RUNDECK_DATABASE_USERNAME: $RUNDECK_DATABASE_USERNAME
      RUNDECK_DATABASE_PASSWORD: $RUNDECK_DATABASE_PASSWORD
      RUNDECK_DATABASE_URL: jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false
      RUNDECK_GRAILS_URL: $GRAILS_URL
      RUNDECK_MAIL_SMTP_HOST: $SMTP_HOST
      RUNDECK_MAIL_SMTP_PORT: $SMTP_PORT
      RUNDECK_MAIL_FROM: $MAIL_FROM
    volumes:
      - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
      - ./server/config/realm.properties:/home/rundeck/server/config/realm.properties:ro
      - ./projects/:/home/rundeck/projects/
      - ./scripts:/home/rundeck/scripts/
      - ./var/logs:/home/rundeck/var/logs/rundeck/
      - ./var/ssh:/home/rundeck/.ssh
      - /home/rdf_portal/rdf_portal-rdf/:/home/rundeck/rdf_portal-rdf/
      - /mnt/nas05/rdf_portal/togovar:/mnt/nas05/rdf_portal/togovar
        # - /mnt/share/togovar/load/virtuoso:/home/rundeck/togovar-rdf/virtuoso/
        # - /root/dev/rundeck/.ssh:/home/rundeck/.ssh/
      - /etc/hosts:/etc/hosts
      - ./var/rundeck:/var/rundeck_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 14440:4440
  mysql:
    image: mysql:5.7
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

